name: Build and Release Godot Game

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Godot
      uses: firebelley/godot-action@v1
      with:
        godot_version: "4.3"

    - name: Extract version from godot.project
      id: version
      run: |
        VERSION=$(grep -oP 'config/version="\K[^"]+' godot.project)
        echo "Extracted version: $VERSION"
        echo "::set-output name=version::$VERSION"

    - name: Build for Windows
      run: |
        godot --export-release "Windows Desktop" build/windows/SumZero.exe

    - name: Build for Linux
      run: |
        godot --export-release "Linux/X11" build/linux/SumZero.x86_64

    - name: Build for Web
      run: |
        godot --export-release "HTML5" build/web/index.html

    - name: Build for Android
      run: |
        godot --export-release "Android" build/android/SumZero.apk

    - name: Generate SHA256 checksums
      id: checksums
      run: |
        echo "::set-output name=windows_sha::$(sha256sum build/windows/game.exe | awk '{print $1}')"
        echo "::set-output name=linux_sha::$(sha256sum build/linux/game.x86_64 | awk '{print $1}')"
        echo "::set-output name=web_sha::$(sha256sum build/web/index.html | awk '{print $1}')"
        echo "::set-output name=android_sha::$(sha256sum build/android/game.apk | awk '{print $1}')"

    - name: Create Release
      uses: actions/create-release@v1
      if: success()
      with:
        tag_name: v${{ steps.version.outputs.version }}
        release_name: Release v${{ steps.version.outputs.version }}
        body: |
          Changelog:
          ${{ github.event.head_commit.message }}

          SHA256 Checksums:
          - Windows: ${{ steps.checksums.outputs.windows_sha }}
          - Linux: ${{ steps.checksums.outputs.linux_sha }}
          - Web: ${{ steps.checksums.outputs.web_sha }}
          - Android: ${{ steps.checksums.outputs.android_sha }}
        draft: false
        prerelease: false

    - name: Upload Windows Artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/windows/SumZero.exe
        asset_name: SumZero-windows.exe
        asset_content_type: application/octet-stream

    - name: Upload Linux Artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/linux/SumZero.x86_64
        asset_name: SumZero-linux.x86_64
        asset_content_type: application/octet-stream

    - name: Upload Web Artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/web/index.html
        asset_name: SumZero-web.zip
        asset_content_type: application/zip

    - name: Upload Android Artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/android/SumZero.apk
        asset_name: SumZero-android.apk
        asset_content_type: application/vnd.android.package-archive
